services:
  postgres:
    image: postgres
    container_name: postgres_auto_care
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=auto_care
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres